sudo: false
os: linux
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
install: pip install tox-travis
stages:
  - environment
  - lint
  - test
  - examples-test
  - build
jobs:
  include:
    - stage: lint
      script: python ci/environment.py
      script: python ci/lint.py
      python:
        - "2.7"
        - "3.5"
        - "3.6"
    - stage: examples-test
      script: python ci/environment.py
      script: tox -e example-py27,example-py35,example-py36
      python:
        - "2.7"
        - "3.5"
        - "3.6"
      name: "Example Tests"
    - stage: build
      script: python ci/build.py
      python:
        - "2.7"
        - "3.5"
        - "3.6"
script:
  python ci/environment.py
  tox