sudo: false
os: linux
language: python
python:
  - 2.7
  - 3.5
  - 3.6
install: python ci/environment.py
         pip install tox-travis
stages:
  - environment
  - lint
  - test
  - examples-test
  - build
jobs:
  include:
    - stage: lint
      script: python ci/lint.py
      python: 2.7
      name: "Lint"
    - stage: lint
      script: python ci/lint.py
      python: 3.5
      name: "Lint"
    - stage: lint
      script: python ci/lint.py
      python: 3.6
      name: "Lint"
    - stage: examples-test
      script: tox -e example-py27,example-py35,example-py36
      python: 2.7
      name: "Example Tests"
    - stage: examples-test
      script: tox -e example-py27,example-py35,example-py36
      python: 3.5
      name: "Example Tests"
    - stage: examples-test
      script: tox -e example-py27,example-py35,example-py36
      python: 3.6
      name: "Example Tests"
    - stage: build
      script: python ci/build.py
      python: 2.7
      name: "Build"
    - stage: build
      script: python ci/build.py
      python: 3.5
      name: "Build"
    - stage: build
      script: python ci/build.py
      python: 3.6
      name: "Build"
    - stage: test
      # Would have deploy code here as well -> PyPi and github if tag  
script:
  python ci/environment.py
  tox