sudo: false
os: linux
language: python
env:
  global: ON_TRAVIS=1
python:
  - 2.7
  - 3.5
  - 3.6
install: python ci/environment.py
         pip install tox-travis
stages:
  - name: environment
  - name: lint
  - name: test
  - name: examples-test
  - name: build
    if: tag =~ ^v\d+\.\d+\.\d+
  - name: gh-pages
    if: tag =~ ^v\d+\.\d+\.\d+

script: skip


jobs:
  fast_finish: true
  include:
    - stage: lint
      script: python ci/lint.py
      python: 2.7
      name: "Lint"

    - stage: lint
      script: python ci/lint.py
      python: 3.5
      name: "Lint"

    - stage: lint
      script: python ci/lint.py
      python: 3.6
      name: "Lint"

    - stage: test
      script: tox -e test-py27
      python: 2.7
      name: "Unit Tests"

    - stage: test
      script: tox -e test-py35
      python: 3.5
      name: "Unit Tests"

    - stage: test
      script: tox -e test-py36
      python: 3.6
      name: "Unit Tests"

    - stage: examples-test
      script: tox -e examples-py27
      python: 2.7
      name: "Example Tests"

    - stage: examples-test
      script: tox -e examples-py35
      python: 3.5
      name: "Example Tests"

    - stage: examples-test
      script: tox -e examples-py36
      python: 3.6
      name: "Example Tests"

    - stage: build
      script: tox -e build-py27
      python: 2.7
      name: "Build"
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
        on:
          tags: true
      deploy:
        provider: pypi
        # user: ...
        # password: ...
        distributions: "sdist bdist_wheel"
        skip_cleanup: true

    - stage: build
      script: tox -e build-py35
      python: 3.5
      name: "Build"
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
        on:
          tags: true
      deploy:
        provider: pypi
        # user: ...
        # password: ...
        distributions: "sdist bdist_wheel"
        skip_cleanup: true

    - stage: build
      script: tox -e build-py36
      python: 3.6
      name: "Build"
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
        on:
          tags: true
      deploy:
        provider: pypi
        # user: ...
        # password: ...
        distributions: "sdist bdist_wheel"
        skip_cleanup: true

    - stage: gh-pages
      script: tox -e gh-pages
      python: 3.6
      name: "Build GitHub pages"
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        keep-history: true
        skip_cleanup: true
        on:
          tags: true

